### ISSUE TITLE
Get online tribune metrics

### ISSUE THREAD

**Issue by carolferreguete** [conceptho/site#18]

**Comment by romulo1984** [comment]
@MayaraViana 

### Dezembro de 2017 - Dezembro de 2018
Tempo médio de carregamento: -71%

---
### 2017 - 2019
Visualizações de página: +103,48%
Usuários: +235,83%
Sessões: +246,18%
Taxa de rejeição: -26,92%

**Comment by mayaraviana** [comment]
Irei pedir issue
