### ISSUE TITLE
Team characters

### ISSUE THREAD

**Issue by romulo1984** [conceptho/site#19]
Criar pixel art da base dos personagens, pensando em como reaproveitar o máximo, mas dar possibilidades em mudar as roupas, cor de pele.

Criar também o rosto dos integrantes. Pra isso, marcar aqui os já finalizados:
- [x] Base

- [x] Mayara
- [x] Jordão
- [x] Andre
- [x] Gabi
- [x] Carol
- [x] José
- [x] Vieira
- [x] Rômulo

**Comment by MayaraViana** [comment]
base: 

![octocatgif](https://user-images.githubusercontent.com/54589016/76126533-10f39a00-5fde-11ea-9521-2e3201d3524c.gif)

**Comment by MayaraViana** [comment]
![octocatgif](https://user-images.githubusercontent.com/54589016/76126706-9e36ee80-5fde-11ea-9cc2-5dec149322a5.gif)

**Comment by mayaraviana** [comment]
Base: 

![octocatgif](https://user-images.githubusercontent.com/54589016/76211338-c132ef80-61e4-11ea-83da-23669d9db328.gif)

**Comment by mayaraviana** [comment]
Jordão: 

![octjordão](https://user-images.githubusercontent.com/54589016/76212167-a2355d00-61e6-11ea-9c9c-9db96aa7b931.gif)

**Comment by mayaraviana** [comment]
Carol:

![carol](https://user-images.githubusercontent.com/54589016/76619550-ed62af00-6509-11ea-8abd-17b3f9b9f270.gif)

**Comment by mayaraviana** [comment]
Eu:

![eumexma](https://user-images.githubusercontent.com/54589016/76619563-f5baea00-6509-11ea-827a-e1c772994f69.gif)

**Comment by mayaraviana** [comment]
Gabi:

![gabi](https://user-images.githubusercontent.com/54589016/76619577-fe132500-6509-11ea-9433-b6ba6c20ed17.gif)

**Comment by mayaraviana** [comment]
Romin:

![octromin](https://user-images.githubusercontent.com/54589016/76778617-e4cbdc00-6788-11ea-8ac9-abe752099b54.gif)

**Comment by mayaraviana** [comment]
Vieira:

![octvieira](https://user-images.githubusercontent.com/54589016/76785949-1d71b280-6795-11ea-893c-b74d43fc1a4d.gif)

**Comment by mayaraviana** [comment]
Zé
![octbomze](https://user-images.githubusercontent.com/54589016/76893053-73645a00-686a-11ea-8e9f-9fd963cdbd36.gif)

**Comment by MayaraViana** [comment]
Andre:

![octmetzen](https://user-images.githubusercontent.com/54589016/76896745-2f288800-6871-11ea-8af1-130d78f18a39.gif)

**Comment by romulo1984** [comment]
@MayaraViana gostei de todos, mas ainda acho que no "i love aws" do Metzen precisa ter uma nuvenzinha. Ficará um pouco difícil de ler se não tiver.

**Comment by MayaraViana** [comment]
Andre: 


![octmetzen](https://user-images.githubusercontent.com/54589016/77484731-09b7f300-6e0a-11ea-9984-d4801820410e.png)

**Comment by mayaraviana** [comment]
Andre:


![octmetzen](https://user-images.githubusercontent.com/54589016/77484775-2522fe00-6e0a-11ea-8f32-8d4a8b54316b.gif)

**Comment by romulo1984** [comment]
Ótimo, fechando a issue.
