### ISSUE TITLE
Boss character

### ISSUE THREAD

**Issue by romulo1984** [conceptho/site#20]
Criar o pixel art do(s) chefe(s). Pensar em algo que facilite a implementação da mecânica do jogo.

**Comment by MayaraViana** [comment]
Pensei em algo simples, bem na ideia do mario, mas algo que conversasse com o cenário também. 

![image](https://user-images.githubusercontent.com/54589016/75884421-89523380-5e03-11ea-80a1-67c5fe46954f.png)

**Gif dele caindo:** 

![backgroundgifcaindo](https://user-images.githubusercontent.com/54589016/75884455-9bcc6d00-5e03-11ea-9919-55a5ca7c5786.gif)

Pensei do boss aparecer aleatoriamente na parte de cima, vários deles caindo e ir desaparecendo na parte de baixo. Assim adiciona uma dificuldade a mais ao jogo.

**Comment by mayaraviana** [comment]
Pensei em algo simples, bem na ideia do mario, mas algo que conversasse com o cenário também. 

![bossinho](https://user-images.githubusercontent.com/54589016/75884683-0d0c2000-5e04-11ea-92f2-e6c5935c6767.png)


**Gif dele caindo:** 

![backgroundgifcaindo](https://user-images.githubusercontent.com/54589016/75884455-9bcc6d00-5e03-11ea-9919-55a5ca7c5786.gif)

Pensei do boss aparecer aleatoriamente na parte de cima, vários deles caindo e ir desaparecendo na parte de baixo. Assim adiciona uma dificuldade a mais ao jogo.

**Comment by romulo1984** [comment]
Eu gostei bastante do boss :) Ficou bem condizente com o cenário.

Já pro caso da animação, que ainda decidiremos mais pra frente na hora de programar o jogo, acho que ficaria mais interessante ele parando no limite do piso, ao invés de cair até sair da tela.
Dessa forma ele bate no piso e pode subir até sumir, e continuaria caindo outros de forma aleatória como você sugeriu.
