### ISSUE TITLE
Infographics vectorization

### ISSUE THREAD

**Issue by carolferreguete** [conceptho/site#21]
Sumary: Produção de infográficos com as seguintes métricas:
Dezembro de 2017 - Dezembro de 2018
Tempo médio de carregamento: -71%
2017 - 2019
Visualizações de página: +103,48%
Usuários: +235,83%
Sessões: +246,18%
Taxa de rejeição: -26,92%

**Comment by mayaraviana** [comment]
![Inforgrafico](https://user-images.githubusercontent.com/54589016/77478496-d458d880-6dfc-11ea-900d-da4cda26f418.png)

Tentei deixar mais neutro, para n brigar muito com os outros elementos do site que ainda vão vir. Tentei fazer como se fosse um sessão do site.

**Comment by mayaraviana** [comment]
@romulo1984

**Comment by romulo1984** [comment]
@MayaraViana Acho que esse infográfico vai aparecer na página do case Tribuna Online, sendo assim, as informações podem ser bem específicas para esse caso.

Vou colocar mais dados aqui sobre o case, e se puder, tente desenhar o infográfico já na configuração da página lá no Figma.
