### ISSUE TITLE
Create support elements for the game

### ISSUE THREAD

**Issue by carolferreguete** [conceptho/site#22]
Summary:
Nessa issue deve-se criar os elementos de apoio para o jogo, sendo:
-Placar
-Corações de Vida
-Mensagem de 404 page error
-Texto tutorial para inicio de jogo
-Game Over

**Comment by mayaraviana** [comment]
A fonte selecionada foi a Press Start 2P oferecida no google fonts.
A escolha dessa fonte é por ele ser gratuita e relembrar tipografia de jogos 8bit.

(https://fonts.google.com/specimen/Press+Start+2P?selection.family=Roboto)

Deixei os elementos mais simples para não ter poluição visual.
Todos os elementos devem ser brancos (#ffff)

Tela montada:

![jogomontado](https://user-images.githubusercontent.com/54589016/77106016-3f6d6e00-69fd-11ea-896e-50864f2e3eac.png)


Tela de game over:
![gameoverscreen](https://user-images.githubusercontent.com/54589016/77106248-8b201780-69fd-11ea-82e0-e7a652f8e626.png)


Coração:
(acho que n vai da para visualizar pq ele é branco, mas apenas para deixar anexado)
![coração](https://user-images.githubusercontent.com/54589016/77106384-c1f62d80-69fd-11ea-84cc-15a2db67f16e.png)

**Comment by mayaraviana** [comment]
@romulo1984

**Comment by romulo1984** [comment]
@MayaraViana eu gostei bastante :)

Convocando todos para verem:
@andremetzen 
@carolferreguete 
@joseslima 
@engylemure 
@v1eira

**Comment by joseslima** [comment]
Gosteeeeeei!

**Comment by v1eira** [comment]
Curti também. Vai ficar bem legal!

**Comment by carolferreguete** [comment]
Irado!

**Comment by romulo1984** [comment]
@MayaraViana vou fechar essa issue, pra mim está finalizada.

Lembra de deixar depois disponível pra gente os fontes, pra quando for usar de fato.
