### ISSUE TITLE
Create character selection

### ISSUE THREAD

**Issue by carolferreguete** [conceptho/site#24]

**Comment by MayaraViana** [comment]
![caracterSelection](https://user-images.githubusercontent.com/54589016/77345870-fdea0500-6d13-11ea-85a7-587672c58e74.png)

**Comment by mayaraviana** [comment]
![caracterSelection](https://user-images.githubusercontent.com/54589016/77345959-2bcf4980-6d14-11ea-806a-8ca9aa5ac905.png)

**Comment by mayaraviana** [comment]
@romulo1984 
@carolferreguete 
@andremetzen 
@joseslima 
@engylemure  
@v1eira

**Comment by mayaraviana** [comment]
Convocando ocês para verem

**Comment by carolferreguete** [comment]
eu amei! Só vi vantagens. 
pq a gabi tem um quadro branco no fundo?

**Comment by mayaraviana** [comment]
é para representar quando um personagem esta selecionado o/

**Comment by romulo1984** [comment]
@MayaraViana não dá pra ver direito o que tem em cima da cabeça do metzen. Talvez fosse interessante colocar o texto dentro de uma nuvem, que vai significar cloud computing também.

**Comment by v1eira** [comment]
Gostei demais!!!

**Comment by mayaraviana** [comment]
![championSelect](https://user-images.githubusercontent.com/54589016/77484658-dd03db80-6e09-11ea-8305-8fb714a06632.png)
  

Achei que ficou melhor msm ;)

**Comment by romulo1984** [comment]
Também achei. Fechando a issue.
