### ISSUE TITLE
Boss Animation

### ISSUE THREAD

**Issue by carolferreguete** [conceptho/site#27]

**Comment by mayaraviana** [comment]
![bossinho](https://user-images.githubusercontent.com/54589016/78787709-2400dd80-7981-11ea-9312-13eec6d91eff.gif)

**Comment by mayaraviana** [comment]
Diminui o tamanho e dei uma testada, achei que ficou melhor agora. 
Não consegui fazer o gif funcionar, n sei se o phaser aceita.

@romulo1984

**Comment by mayaraviana** [comment]
![BossSprite](https://user-images.githubusercontent.com/54589016/78789545-a8546000-7983-11ea-96d0-1c0c9d44c0fe.png)

**Comment by romulo1984** [comment]
@MayaraViana acho que ficou bom no jogo, então estou fechando a issue.
