### ISSUE TITLE
Sprites Organization

### ISSUE THREAD

**Issue by carolferreguete** [conceptho/site#29]
Summary: nessa issue é preciso organizar os sprites de todos os personagens de acordo com o formato que o phaser pede.

**Comment by mayaraviana** [comment]
![ze](https://user-images.githubusercontent.com/54589016/78921216-f5f7c800-7a6a-11ea-8ecd-4966f17f5a68.png)
![Romin](https://user-images.githubusercontent.com/54589016/78921221-f6905e80-7a6a-11ea-8018-48f0a2b32371.png)
![vieira](https://user-images.githubusercontent.com/54589016/78921224-f728f500-7a6a-11ea-9256-77ea7fa1a558.png)
![me](https://user-images.githubusercontent.com/54589016/78921232-f8f2b880-7a6a-11ea-89f3-0f4cadcfc558.png)
![Carol](https://user-images.githubusercontent.com/54589016/78921233-f98b4f00-7a6a-11ea-97c2-6622ae252864.png)
![gabi](https://user-images.githubusercontent.com/54589016/78921234-f98b4f00-7a6a-11ea-8bf6-ac18eaefef28.png)
![Jordão](https://user-images.githubusercontent.com/54589016/78921237-fa23e580-7a6a-11ea-85bc-6a6552ce8072.png)

**Comment by mayaraviana** [comment]
![Olivia2](https://user-images.githubusercontent.com/54589016/78921301-16c01d80-7a6b-11ea-9395-40d1df178546.png)
 
O frame da Olivia é 35 de altura x 30 de largura

**Comment by mayaraviana** [comment]
Tela de seleção:

![Seletor](https://user-images.githubusercontent.com/54589016/78921369-2dff0b00-7a6b-11ea-8e22-430a89aac78e.png)

**Comment by mayaraviana** [comment]
@romulo1984

**Comment by romulo1984** [comment]
![Captura de Tela_Área de Seleção_20200409144013](https://user-images.githubusercontent.com/1641962/78925774-5d654600-7a72-11ea-826c-e78439a9dc41.png)

Tô achando aquele espaço ali muuuito apertadinho, não acha?
Se tiver como equilibrar melhor os paddings, seria interessante.

Ah, e tá faltando o Metzen nos sprites, não?

**Comment by mayaraviana** [comment]
![Metzen](https://user-images.githubusercontent.com/54589016/78925989-b503b180-7a72-11ea-90d9-151b99b47a33.png)

**Comment by mayaraviana** [comment]
oxe, n enviou :s

**Comment by MayaraViana** [comment]
![Seletor](https://user-images.githubusercontent.com/54589016/78927787-d4e8a480-7a75-11ea-8056-131162021818.png)

**Comment by mayaraviana** [comment]
![Seletor](https://user-images.githubusercontent.com/54589016/78927942-1da05d80-7a76-11ea-8806-50f6cae6598f.png)

**Comment by romulo1984** [comment]
@MayaraViana ufa, agora consigo respirar, kkkkk. Eu sei, eu tenho problemas.

**Comment by mayaraviana** [comment]
KKKKKKKKKKKKKKKKKKKKKKK
