### ISSUE TITLE
Reference search

### ISSUE THREAD

**Issue by carolferreguete** [conceptho/site#6]
A ideia é buscar o maior número de referências de sites bem diferentes, que usam bastante a criatividade para apresentar suas marcas. O meu pensamento é sair do lugar comum e ousar bastante nas propostas, mesmo que nem todas elas sejam aplicadas.

**Comment by romulo1984** [comment]
Lembrando que essa etapa é constante, mas a busca inicial já foi completada, então fecharei essa issue.
